name: Go Build and Docker Push

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Build for Linux
        run: |
          go build .

      - name: Build and push Docker image
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/bubblelife:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_NAME
